#!/bin/sh
# Copyright 2024 ruhop contributors
# Licensed under the Apache License, Version 2.0
#
# Generate ruhop TOML configuration from UCI settings

. /lib/functions.sh

CONFIG_FILE="${1:-/etc/ruhop/ruhop.toml}"
UCI_CONFIG="ruhop"

# Helper functions
uci_get_bool() {
    local val
    config_get val "$1" "$2" "$3"
    [ "$val" = "1" ] && echo "true" || echo "false"
}

uci_get_list() {
    local section="$1"
    local option="$2"
    local result=""
    local cb_handler

    cb_handler() {
        if [ -n "$result" ]; then
            result="$result, \"$1\""
        else
            result="\"$1\""
        fi
    }

    config_list_foreach "$section" "$option" cb_handler
    echo "$result"
}

# Load UCI config
config_load "$UCI_CONFIG"

# Get mode
config_get MODE main mode "client"

# Create config directory if needed
mkdir -p "$(dirname "$CONFIG_FILE")"

# Start generating TOML
cat > "$CONFIG_FILE" << 'HEADER'
# Ruhop VPN Configuration
# Generated by luci-app-ruhop
# Do not edit directly - use LuCI interface

HEADER

# [common] section
echo "[common]" >> "$CONFIG_FILE"

config_get KEY common key ""
if [ -n "$KEY" ]; then
    echo "key = \"$KEY\"" >> "$CONFIG_FILE"
fi

config_get MTU common mtu "1400"
echo "mtu = $MTU" >> "$CONFIG_FILE"

config_get LOG_LEVEL common log_level "info"
echo "log_level = \"$LOG_LEVEL\"" >> "$CONFIG_FILE"

config_get LOG_FILE common log_file ""
if [ -n "$LOG_FILE" ]; then
    echo "log_file = \"$LOG_FILE\"" >> "$CONFIG_FILE"
    config_get LOG_ROTATION common log_rotation "daily"
    echo "log_rotation = \"$LOG_ROTATION\"" >> "$CONFIG_FILE"
fi

config_get OBFUSCATION common obfuscation "0"
[ "$OBFUSCATION" = "1" ] && echo "obfuscation = true" >> "$CONFIG_FILE"

config_get HEARTBEAT common heartbeat_interval "30"
echo "heartbeat_interval = $HEARTBEAT" >> "$CONFIG_FILE"

config_get TUN_DEVICE common tun_device ""
if [ -n "$TUN_DEVICE" ]; then
    echo "tun_device = \"$TUN_DEVICE\"" >> "$CONFIG_FILE"
fi

config_get USE_NFTABLES common use_nftables ""
if [ "$USE_NFTABLES" = "1" ]; then
    echo "use_nftables = true" >> "$CONFIG_FILE"
elif [ "$USE_NFTABLES" = "0" ]; then
    echo "use_nftables = false" >> "$CONFIG_FILE"
fi

echo "" >> "$CONFIG_FILE"

# Mode-specific sections
if [ "$MODE" = "server" ]; then
    # [server] section
    echo "[server]" >> "$CONFIG_FILE"

    config_get LISTEN server listen "0.0.0.0"
    echo "listen = \"$LISTEN\"" >> "$CONFIG_FILE"

    config_get PORT_START server port_start "4096"
    config_get PORT_END server port_end "4196"
    echo "port_range = [$PORT_START, $PORT_END]" >> "$CONFIG_FILE"

    config_get TUNNEL_NETWORK server tunnel_network "10.0.0.0/24"
    echo "tunnel_network = \"$TUNNEL_NETWORK\"" >> "$CONFIG_FILE"

    config_get TUNNEL_IP server tunnel_ip ""
    if [ -n "$TUNNEL_IP" ]; then
        echo "tunnel_ip = \"$TUNNEL_IP\"" >> "$CONFIG_FILE"
    fi

    config_get MAX_CLIENTS server max_clients "100"
    echo "max_clients = $MAX_CLIENTS" >> "$CONFIG_FILE"

    config_get ENABLE_NAT server enable_nat "1"
    [ "$ENABLE_NAT" = "1" ] && echo "enable_nat = true" >> "$CONFIG_FILE" || echo "enable_nat = false" >> "$CONFIG_FILE"

    config_get NAT_INTERFACE server nat_interface ""
    if [ -n "$NAT_INTERFACE" ]; then
        echo "nat_interface = \"$NAT_INTERFACE\"" >> "$CONFIG_FILE"
    fi

    config_get DNS_PROXY server dns_proxy "0"
    [ "$DNS_PROXY" = "1" ] && echo "dns_proxy = true" >> "$CONFIG_FILE"

    DNS_SERVERS=$(uci_get_list server dns_servers)
    if [ -n "$DNS_SERVERS" ]; then
        echo "dns_servers = [$DNS_SERVERS]" >> "$CONFIG_FILE"
    fi

else
    # [client] section
    echo "[client]" >> "$CONFIG_FILE"

    # Handle server list (can be single or multiple)
    SERVERS=$(uci_get_list client server)
    if [ -n "$SERVERS" ]; then
        # Check if single or multiple servers
        SERVER_COUNT=$(echo "$SERVERS" | tr ',' '\n' | wc -l)
        if [ "$SERVER_COUNT" -eq 1 ]; then
            # Single server - use simple string
            echo "server = $SERVERS" >> "$CONFIG_FILE"
        else
            # Multiple servers - use array
            echo "server = [$SERVERS]" >> "$CONFIG_FILE"
        fi
    fi

    config_get PORT_START client port_start "4096"
    config_get PORT_END client port_end "4196"
    echo "port_range = [$PORT_START, $PORT_END]" >> "$CONFIG_FILE"

    config_get TUNNEL_IP client tunnel_ip ""
    if [ -n "$TUNNEL_IP" ]; then
        echo "tunnel_ip = \"$TUNNEL_IP\"" >> "$CONFIG_FILE"
    fi

    config_get ROUTE_ALL client route_all_traffic "1"
    [ "$ROUTE_ALL" = "1" ] && echo "route_all_traffic = true" >> "$CONFIG_FILE" || echo "route_all_traffic = false" >> "$CONFIG_FILE"

    EXCLUDED_ROUTES=$(uci_get_list client excluded_routes)
    if [ -n "$EXCLUDED_ROUTES" ]; then
        echo "excluded_routes = [$EXCLUDED_ROUTES]" >> "$CONFIG_FILE"
    fi

    DNS_LIST=$(uci_get_list client dns)
    if [ -n "$DNS_LIST" ]; then
        echo "dns = [$DNS_LIST]" >> "$CONFIG_FILE"
    fi

    config_get MSS_FIX client mss_fix "0"
    [ "$MSS_FIX" = "1" ] && echo "mss_fix = true" >> "$CONFIG_FILE"

    config_get AUTO_RECONNECT client auto_reconnect "1"
    [ "$AUTO_RECONNECT" = "1" ] && echo "auto_reconnect = true" >> "$CONFIG_FILE" || echo "auto_reconnect = false" >> "$CONFIG_FILE"

    config_get MAX_RECONNECT client max_reconnect_attempts "0"
    echo "max_reconnect_attempts = $MAX_RECONNECT" >> "$CONFIG_FILE"

    config_get RECONNECT_DELAY client reconnect_delay "5"
    echo "reconnect_delay = $RECONNECT_DELAY" >> "$CONFIG_FILE"

    config_get ON_CONNECT client on_connect ""
    if [ -n "$ON_CONNECT" ]; then
        echo "on_connect = \"$ON_CONNECT\"" >> "$CONFIG_FILE"
    fi

    config_get ON_DISCONNECT client on_disconnect ""
    if [ -n "$ON_DISCONNECT" ]; then
        echo "on_disconnect = \"$ON_DISCONNECT\"" >> "$CONFIG_FILE"
    fi

    # [client.probe] section
    config_get PROBE_ENABLED probe probe_enabled "0"
    if [ "$PROBE_ENABLED" = "1" ]; then
        echo "" >> "$CONFIG_FILE"
        echo "[client.probe]" >> "$CONFIG_FILE"

        config_get PROBE_INTERVAL probe probe_interval "10"
        echo "interval = $PROBE_INTERVAL" >> "$CONFIG_FILE"

        config_get PROBE_THRESHOLD probe probe_threshold "0.5"
        echo "threshold = $PROBE_THRESHOLD" >> "$CONFIG_FILE"

        config_get PROBE_BLACKLIST probe probe_blacklist_duration "300"
        echo "blacklist_duration = $PROBE_BLACKLIST" >> "$CONFIG_FILE"

        config_get PROBE_MIN probe probe_min_probes "3"
        echo "min_probes = $PROBE_MIN" >> "$CONFIG_FILE"
    fi

    # [client.dns_proxy] section
    config_get DNS_PROXY_ENABLED client_dns_proxy dns_proxy_enabled "0"
    if [ "$DNS_PROXY_ENABLED" = "1" ]; then
        echo "" >> "$CONFIG_FILE"
        echo "[client.dns_proxy]" >> "$CONFIG_FILE"
        echo "enabled = true" >> "$CONFIG_FILE"

        config_get DNS_PROXY_PORT client_dns_proxy dns_proxy_port "53"
        echo "port = $DNS_PROXY_PORT" >> "$CONFIG_FILE"

        config_get DNS_PROXY_IPV6 client_dns_proxy dns_proxy_filter_ipv6 "0"
        [ "$DNS_PROXY_IPV6" = "1" ] && echo "filter_ipv6 = true" >> "$CONFIG_FILE"

        config_get DNS_PROXY_IPSET client_dns_proxy dns_proxy_ipset ""
        if [ -n "$DNS_PROXY_IPSET" ]; then
            echo "ipset = \"$DNS_PROXY_IPSET\"" >> "$CONFIG_FILE"
        fi
    fi
fi

echo "" >> "$CONFIG_FILE"
echo "# End of generated configuration" >> "$CONFIG_FILE"

exit 0
